import { z } from "zod";

import { SERVICE, apiPost } from "../../../../helpers/api.client.js";
import type { ToolDefinition } from "../../../../types/tool.types.js";
import { toolRegistry } from "../../../registry.js";

const schema = z.object({
  event_type: z
    .number()
    .int()
    .min(1)
    .max(6)
    .describe(
      "Event type code: 1=meeting, 2=holiday, 3=birthday, 4=appointment, 5=work anniversary, 6=reminder.",
    ),
});

interface PublicEventByType {
  id: number;
  title: string;
  description: string | null;
  start_date: string;
  end_date: string | null;
  is_all_day: boolean;
  event_type: number;
  status: number;
  created_at: string | null;
}

interface RawEvent {
  id?: number;
  title?: string;
  description?: string | null;
  start_date?: string;
  end_date?: string | null;
  is_all_day?: boolean;
  event_type?: number;
  status?: number;
  createdAt?: string | null;
}

interface EventsByTypeResponse {
  message: Array<{ msg: string; status: boolean; data: RawEvent[] }>;
}

interface ListByTypeResult {
  event_type: number;
  total: number;
  events: PublicEventByType[];
}

export const listCalendarEventsByTypeTool: ToolDefinition<
  typeof schema,
  ListByTypeResult
> = {
  name: "list_calendar_events_by_type",
  title:
    "Filter public calendar events by type — meeting, holiday, birthday, appointment, anniversary, reminder",
  description:
    "Returns public calendar events filtered to a single event_type (1-6). Useful when you " +
    "know exactly what category of event you want. " +
    "\n\nUSE THIS TOOL TO: 'show all meetings on the company calendar', 'list all reminders', " +
    "or any single-category drill-down. " +
    "\n\nNOTE: Birthdays (3) and work anniversaries (5) are ONLY auto-generated by " +
    "list_public_calendar_events at fetch time — they are NOT stored as rows, so this endpoint " +
    "will return an empty list for those types. For birthdays/anniversaries always use " +
    "list_public_calendar_events. For holidays specifically, list_holidays is a thin wrapper " +
    "around event_type=2.",
  inputSchema: schema,
  annotations: { readOnlyHint: true, idempotentHint: true },
  meta: { version: "1.0.0", tags: ["calendar", "events", "filter"] },

  handler: async (input, ctx) => {
    const res = await apiPost<EventsByTypeResponse>(
      `${SERVICE.ACTIVITY_CALENDAR}/getPublicEventsByType`,
      { event_type: input.event_type },
      ctx,
      { injectCompanyContext: false },
    );

    const records = res?.message?.[0]?.data ?? [];
    const events: PublicEventByType[] = records.map((e) => ({
      id: e.id ?? 0,
      title: e.title ?? "Untitled",
      description: e.description ?? null,
      start_date: e.start_date ?? "",
      end_date: e.end_date ?? null,
      is_all_day: e.is_all_day ?? false,
      event_type: e.event_type ?? input.event_type,
      status: e.status ?? 1,
      created_at: e.createdAt ?? null,
    }));

    return { event_type: input.event_type, total: events.length, events };
  },
};

toolRegistry.register(listCalendarEventsByTypeTool);
